from setuptools import setup, find_packages

setup(
    name="fida",
    version="0.1",
    packages=find_packages(),
    url="https://github.com/pablomitchell/fida",
    license="MIT",
    author="Pablo Mitchell",
    author_email="pablo.mitchell@gmail.com",
    description="Financial Data Accessor Code in Python",
    install_requires=[
        "loguru",
        "lxml",
        "matplotlib",
        "nest_asyncio",
        "numba",
        "numpy",
        "pandas",
        "pandas-datareader",
        "pyrate_limiter",
        "requests_cache",
        "requests_ratelimiter",
        "scipy",
        "setuptools",
        "tqdm",
        "tiingo",
        "yfinance",
    ],
)
